### ISSUE TITLE
libfprint package

### ISSUE THREAD

**Issue by wojtekka** [mrrbrilliant/ft9201-static#2]
Hello,

README file mentions that the package is a proprietary asset. Is this file distributed under an explicit agreement with FocalTech? Since the original libfprint is distributed under the terms of LGPL, does the same licence apply to contents of this package? Or is it a drop-in replacement for libfprint developed without the use of original code?

**Comment by mrrbrilliant** [comment]
My company, KOOMPI which is [a laptop brand in Cambodia focusing on open source and Linux](koompi.com), used to work with a Chinese laptop vendor whose fingerprint is by FocalTech. We didn't have any chances to work with FocalTech directly. Initially there was no Linux support at all. Through a lot of communications we could get the compiled binary from FocalTech through the laptop vendor. We used Arch and requested an Arch package but they gave a Deb. For some reason, the project with that specific laptop model didn't continue. I am not sure about its License since all I got was just a binary and it had to meet a very specific condition to work which means the system must never update to keep the driver running. During that time, there were no legal notices or NDA or mentioned that must not distribute so I don't know. I stated proprietary because there was no source code available so to be safe I need to mention that the binary is owned by FocalTech.

Thank you.

**Comment by wojtekka** [comment]
Thank you for the thorough answer. I was wondering if the package in question could be used to develop an open source driver for FocalTech's fingerprint readers as it contains the firmware required for the MCUs inside the readers, but sadly, it seems that there's no straightforward answer.
